ATOMS:
  askl_classifier:
    docker_file: 'docker_askl_classifier'
    docker_entrypoint: 'entrypoint_askl_classifier.py'
    image_name: 'classification_autosklearn'
    image_tag: 'class_askl'
  lgbm_classifier:
    docker_file: 'docker_lgbm_classifier'
    docker_entrypoint: 'entrypoint_lgbm_classifier.py'
    image_name: 'classification_lgbm'
    image_tag: 'class_lgbm'
  logisticRegression_classifier:
    docker_file: 'docker_logisticRegression_classifier'
    docker_entrypoint: 'entrypoint_logisticRegression_classifier.py'
    image_name: 'classification_sklearn_logisticregression'
    image_tag: 'class_skl_logreg'
  xgb_classifier:
    docker_file: 'docker_xgb_classifier'
    docker_entrypoint: 'entrypoint_xgb_classifier.py'
    image_name: 'classification_xgboost'
    image_tag: 'class_xgb'
  lda_classifier:
    docker_file: 'docker_LDA_classifier'
    docker_entrypoint: 'entrypoint_LDA_classifier.py'
    image_name: 'classification_lda'
    image_tag: 'class_lda'
  qda_classifier:
    docker_file: 'docker_QDA_classifier'
    docker_entrypoint: 'entrypoint_QDA_classifier.py'
    image_name: 'classification_qda'
    image_tag: 'class_qda'
  dummy_classifier:
    docker_file: 'docker_dummy_classifier'
    docker_entrypoint: 'entrypoint_dummy_classifier.py'
    image_name: 'classification_dummy'
    image_tag: 'class_dummy'
SCORING:
  sklearn_scorer:
    docker_file: 'docker_sklearn_scorer'
    docker_entrypoint: 'entrypoint_sklearn_scorer.py'
    image_name: 'scorer_sklearn'
    image_tag: 'scorer_skl'
  xgb_scorer:
    docker_file: 'docker_xgboost_scorer'
    docker_entrypoint: 'entrypoint_xgb_scorer.py'
    image_name: 'scorer_xgboost'
    image_tag: 'scorer_xgb'
  lgbm_scorer:
    docker_file: 'docker_lgbm_scorer'
    docker_entrypoint: 'entrypoint_lgbm_scorer.py'
    image_name: 'scorer_lightgbm'
    image_tag: 'scorer_lgbm'
PREPROCESS:
  string2int_encoder:
    docker_file: 'docker_string2int_encoder'
    docker_entrypoint: 'entrypoint_string2int_encoder.py'
    image_name: 'encoder_string2int'
    image_tag: 'encoder_str2int'
  onehot_encoder:
    docker_file: 'docker_onehot_encoder'
    docker_entrypoint: 'entrypoint_onehot_encoder.py'
    image_name: 'encoder_onehot'
    image_tag: 'encoder_onehot'
  data_evaluator:
    docker_file: 'docker_data_evaluator'
    docker_entrypoint: 'entrypoint_data_evaluator.py'
    image_name: 'data_evaluator'
    image_tag: 'data_evaluator'
POSTPROCESS:
  aggregator:
    docker_file: 'docker_aggregator'
    docker_entrypoint: 'entrypoint_aggregator.py'
    image_name: 'aggregator'
    image_tag: 'aggregator'