steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_ffnngpu:class_ffnngpu', '-f', './train/docker_ffnngpu_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/aggregator:aggregator', '-f', './postprocess/docker_aggregator', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/data_evaluator:data_evaluator', '-f', './preprocess/docker_data_evaluator', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/scorer_lightgbm:scorer_lgbm', '-f', './score/docker_lgbm_scorer', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/scorer_sklearn:scorer_skl', '-f', './score/docker_sklearn_scorer', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/scorer_xgboost:scorer_xgb', '-f', './score/docker_xgboost_scorer', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/scorer_tensorflow:scorer_tf', '-f', './score/docker_tensorflow_scorer', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_autosklearn:class_askl', '-f', './train/docker_askl_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_dummy:class_dummy', '-f', './train/docker_dummy_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_lda:class_lda', '-f', './train/docker_LDA_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_lgbm:class_lgbm', '-f', './train/docker_lgbm_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_rf:class_rf', '-f', './train/docker_randomforest_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_sklearn_logisticregression:class_skl_logreg', '-f', './train/docker_logisticRegression_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_qda:class_qda', '-f', './train/docker_QDA_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_xgboost:class_xgb', '-f', './train/docker_xgb_classifier', '.' ]
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/classification_ffnn:class_ffnn', '-f', './train/docker_ffnn_classifier', '.' ]
  timeout: 600s
images:
  - 'gcr.io/$PROJECT_ID/classification_ffnngpu:class_ffnngpu'
  - 'gcr.io/$PROJECT_ID/aggregator:aggregator'
  - 'gcr.io/$PROJECT_ID/data_evaluator:data_evaluator'
  - 'gcr.io/$PROJECT_ID/scorer_lightgbm:scorer_lgbm'
  - 'gcr.io/$PROJECT_ID/scorer_sklearn:scorer_skl'
  - 'gcr.io/$PROJECT_ID/scorer_xgboost:scorer_xgb'
  - 'gcr.io/$PROJECT_ID/scorer_tensorflow:scorer_tf'
  - 'gcr.io/$PROJECT_ID/classification_autosklearn:class_askl'
  - 'gcr.io/$PROJECT_ID/classification_dummy:class_dummy'
  - 'gcr.io/$PROJECT_ID/classification_lda:class_lda'
  - 'gcr.io/$PROJECT_ID/classification_lgbm:class_lgbm'
  - 'gcr.io/$PROJECT_ID/classification_rf:class_rf'
  - 'gcr.io/$PROJECT_ID/classification_sklearn_logisticregression:class_skl_logreg'
  - 'gcr.io/$PROJECT_ID/classification_qda:class_qda'
  - 'gcr.io/$PROJECT_ID/classification_xgboost:class_xgb'
  - 'gcr.io/$PROJECT_ID/classification_ffnn:class_ffnn'
timeout: 3600s